indenture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('listings/', include('listings.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from .views import PropertyCreateView, PropertyUpdateView, PropertyDetailView, PropertyDeleteView, PropertySearchView, ServiceCreateView, ServiceUpdateView, ServiceDeleteView, ServiceSearchView

app_name = 'listing'

urlpatterns = [
    path('property/<int:pk>', PropertyDetailView.as_view(), name='property'),
    path('property/create', PropertyCreateView.as_view(), name='create_property'),
    path('property/update/<int:pk>', PropertyUpdateView.as_view(), name='update_property'),
    path('property/delete/<int:pk>',PropertyDeleteView.as_view(), name='delete_property'),
    path('property/search', PropertySearchView.as_view(), name='search_property'),
    path('service/create', ServiceCreateView.as_view(), name='create_service'),
    path('service/update/<int:pk>', ServiceUpdateView.as_view(), name='update_service'),
    path('service/delete/<int:pk>', ServiceDeleteView.as_view(), name='delete_service'),
    path('service/search', ServiceSearchView.as_view(), name='search_service')
]

main/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name='index'),
]

profiles/urls.py
from django.urls import path
from .views import CreateProfileView, UpdateProfileView, ProfileDetailView

app_name = 'profile'

urlpatterns = [
    path('', ProfileDetailView.as_view(), name='profile'),
    path('create', CreateProfileView.as_view(), name='create'),
    path('update', UpdateProfileView.as_view(), name='update'),
]

users/urls.py
from django.urls import path
from .views import SignUpView, SignInView, SignOutView

app_name = 'users'

urlpatterns = [
    path('signup', SignUpView.as_view(), name='signup'),
    path('signin', SignInView.as_view(), name='signin'),
    path('signout', SignOutView.as_view(), name='signout'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    email = models.EmailField()
    profile_picture = models.ImageField(upload_to='assets/profile_pictures/', blank=True)
    phone_no = models.CharField(max_length=15)
    country = models.CharField(max_length=20)
    city = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.user} | {self.name} | {self.email}'

profiles/forms.py
# forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_picture', 'name', 'email', 'phone_no', 'country', 'city']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control', 'placeholder': field.replace('_', ' ').capitalize()})
            self.fields[field].label = ''

    def clean_phone_no(self):
        phone_no = self.cleaned_data.get('phone_no')
        if not phone_no.isdigit():
            raise forms.ValidationError(
                'Phone number must contain only numeric characters.')
        return phone_no

profiles/views.py
from django.db.models.base import Model as Model
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Profile
from .forms import ProfileForm
from listings.models import Property, Service


class CreateProfileView(CreateView, LoginRequiredMixin):
    form_class = ProfileForm
    template_name = 'create_profile.html'
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    

class UpdateProfileView(UpdateView):
    form_class = ProfileForm
    template_name = 'update_profile.html'
    success_url = '/'

    def get_object(self, queryset=None):
        return Profile.objects.get(user=self.request.user)


class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'profile.html'
    context_object_name = 'profile'

    def get_object(self, queryset=None):
        return Profile.objects.get(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data.update({'properties': Property.objects.filter(user_profile=Profile.objects.get(user=self.request.user)),
                    'services': Service.objects.filter(user_profile=Profile.objects.get(user=self.request.user))})
        return data

templates/confirm.html
{% extends 'layout.html' %}

{% block title %}Confirm{% endblock %}

{% block content %}
<div class="vh-100 d-flex align-items-center justify-content-center">
    <div>
        <h1>Sign Out</h1>
        <form method="post">
            {% csrf_token %}
            Do you really want to proceed?
            <button type="reset" class="btn btn-dark" onclick="location.href='/'">Cancel</button>
            <input type="submit" value="Confirm" class="btn btn-dark">
        </form>
    </div>
</div>
{% endblock %}

templates/create_profile.html
{% extends 'layout.html' %}

{% block title %}Create Profile{% endblock %}

{% block content %}
<div class="vh-100 d-flex align-items-center justify-content-center">
    <div>
        <h1>Create Profile</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create" class="btn btn-dark">
        </form>
    </div>
</div>
{% endblock %}

templates/create_property.html
{% extends 'layout.html' %}

{% block title %}Create Property{% endblock %}

{% block content %}
<div class="d-flex justify-content-center" style="margin: 90px">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" class="btn btn-dark">
    </form>
</div>
{% endblock %}

templates/create_service.html
{% extends 'layout.html' %}

{% block title %}Create Service{% endblock %}

{% block content %}
<div class="d-flex justify-content-center" style="margin: 90px">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" class="btn btn-dark">
    </form>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container-fluid d-flex align-items-center justify-content-center vh-100">
    <div class="text-center">
        <h1>Indenture</h1>
        <p style="font-size: 20px;">Unlocking Dreams, One Key at a Time: Your Home Journey Begins Here!</p>
        <div>
            <a class="btn btn-dark" href="{% url 'listing:search_property' %}">Search Property</a>
            <a class="btn btn-dark" href="{% url 'listing:search_service' %}">Search Services</a>
        </div>
    </div>
</div>
{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>Indenture - {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Indenture</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Property
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'listing:search_property' %}">Search Property</a></li>
                            <li><a class="dropdown-item" href="{% url 'listing:create_property' %}">Create Property Listing</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Service
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'listing:search_service' %}">Search Service</a></li>
                            <li><a class="dropdown-item" href="{% url 'listing:create_service' %}">Create Service Listing</a></li>
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Profile
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'profile:profile' %}">Visit Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'profile:update' %}">Update Profile</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:signout' %}">Sign out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:signout' %}">Sign in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:signout' %}">Sign up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/profile.html
{% extends 'layout.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="d-flex align-items-center justify-content-center" style="min-height: 100vh;">
    <div class="card" style="max-width: 600px; width: 100%;">
        <img src="{{ profile.profile_picture.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ profile.name }}</h5>
            <p class="card-text">@{{ profile.user }}</p>
        </div>
        <center>
            <h4>Properties Listed</h4>
        </center>
        <ul class="list-group list-group-flush">
            <center>
            {% for property in properties %}
            <div class="card w-50">
                <div class="card-body">
                    <h5 class="card-title">{{ property.address }}</h5>
                    <p class="card-text">price: {{ property.price }}, address: {{ property.address }}</p>
                    <div style="display: flex; gap: 10px; justify-content: center;">
                        <a href="{% url 'listing:property' pk=property.id %}" class="btn btn-dark">Visit</a>
                        <a href="tel:{{property.user_profile.phone_no}}" class="btn btn-dark">Call</a>
                        {% if property.user_profile.user == user %}
                            <a class="btn btn-dark" href="{% url 'listing:update_property' pk=property.id %}">Update</a>
                            <form action="{% url 'listing:delete_property' pk=property.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-dark">delete</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% empty %}
                <p>No properties listed</p>
            {% endfor %}
            </center>
        </ul>
        <center>
            <h4>Services Offered</h4>
        </center>
        <div class="list-group list-group-flush">
            <center>
                {% for service in services %}
                    <div class="card w-50">
                        <div class="card-body">
                            <h5 class="card-title">{{ service.title }} in {{ service.city }}, {{ service.country }}</h5>
                            <p class="card-text">Available location: {{ service.available_location }}, google profile link: <a href="{{ service.google_profile }}">{{ service.google_profile }}</a></p>
                            <div style="display: flex; gap: 10px; justify-content: center;">
                                <a class="btn btn-dark" href="tel:{{ service.user_profile.phone_no }}">Call</a>
                                {% if service.user_profile.user == user %}
                                    <a class="btn btn-dark" href="{% url 'listing:update_service' pk=service.id %}">Update</a>
                                    <form action="{% url 'listing:delete_service' pk=service.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-dark">delete</button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </center>
        </div>
    </div>
</div>
{% endblock %}

templates/property.html
{% extends 'layout.html' %}

{% block title %}{{ property.property_type }} For {{ property.transaction_type }}{% endblock %}

{% block content %}
<div class="d-flexjustify-content-center">
    <div class="container mt-5">
        <div class="card">
            <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ property.picture1.url }}" class="d-block w-100" alt="Slide 1">
                    </div>
                    {% if property.picture2 %}
                        <div class="carousel-item">
                            <img src="{{ property.picture2.url }}" class="d-block w-100" alt="Slide 2">
                        </div>
                    {% endif %}
                    {% if property.picture3 %}
                    <div class="carousel-item">
                        <img src="{{ property.picture3.url }}" class="d-block w-100" alt="Slide 3">
                    </div>
                    {% endif %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
    
            <div class="card-body">
                <h5 class="card-title">{{ property.property_type }} for {{ property.transaction_type }}</h5>
                <h5>{{ property.price }} INR</h5>
                <p class="card-text"><b>Address:</b> {{ property.address }}</p>
                <p class="card-text"><b>Description:</b> {{ property.description }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/search_property.html
{% extends 'layout.html' %}

{% block title %} Signin {% endblock %}

{% block content %}
<div class="d-flex justify-content-center" style="margin-top: 90px; display: flex; flex-direction: column;">
    <form method="get" action="{% url 'listing:search_property' %}">
        <input type="text" name="address" placeholder="Address">
        <input type="text" name="property_type" placeholder="Property Type">
        <input type="text" name="transaction_type" placeholder="Transaction Type">
        <input type="number" name="bhk" placeholder="BHK" min="1">
        <input type="number" name="price" placeholder="Max Price" min="5000">
        <button type="submit" class="btn btn-dark">Search</button>
    </form>
    <div style="display: flex; flex-direction: column; align-items: center; margin-top: 30px;">
        {% for property in properties %}
        <div class="card w-50">
            <div class="card-body">
                <h5 class="card-title">{{ property.address }}</h5>
                <p class="card-text">price: {{ property.price }}, address: {{ property.address }}</p>
                <div style="display: flex; gap: 10px; justify-content: center;">
                    <a href="{% url 'listing:property' pk=property.id %}" class="btn btn-dark">Visit</a>
                    <a href="tel:{{property.user_profile.phone_no}}" class="btn btn-dark">Call</a>
                    {% if property.user_profile.user == user %}
                    <a class="btn btn-dark" href="{% url 'listing:update_property' pk=property.id %}">Update</a>
                    <form action="{% url 'listing:delete_property' pk=property.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-dark">delete</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
        {% empty %}
            <p>No properties listed</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/search_service.html
{% extends 'layout.html' %}

{% block title %} Signin {% endblock %}

{% block content %}
<div class="d-flex justify-content-center" style="margin-top: 90px; display: flex; flex-direction: column;">
    <form action="{% url 'listing:search_service' %}" method="get">
        <input type="text" placeholder="Title" name="q">
        <input type="text" placeholder="City" name="city">
        <input type="text" placeholder="Country" name="country">
        <input type="text" placeholder="Available Location" name="available_location">
        <input type="submit" value="Search" class="btn btn-dark">
    </form>
    <div style="display: flex; flex-direction: column; align-items: center; margin-top: 30px;">
        {% for service in services %}
        <div class="card w-50">
            <div class="card-body">
                <h5 class="card-title">{{ service.title }} in {{ service.city }}, {{ service.country }}</h5>
                <p class="card-text">Available location: {{ service.available_location }}, google profile link: <a
                        href="{{ service.google_profile }}">{{ service.google_profile }}</a></p>
                <div style="display: flex; gap: 10px; justify-content: center;">
                    <a class="btn btn-dark" href="tel:{{ service.user_profile.phone_no }}">Call</a>
                    {% if service.user_profile.user == user %}
                    <a class="btn btn-dark" href="{% url 'listing:update_service' pk=service.id %}">Update</a>
                    <form action="{% url 'listing:delete_service' pk=service.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-dark">delete</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
        {% empty %}
            <p>No properties listed</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/signin.html
{% extends 'layout.html' %}

{% block title %} Signin {% endblock %}

{% block content %}
<div class="vh-100 d-flex align-items-center justify-content-center">
    <div>
        <h1>Sign In</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sign In" class="btn btn-dark">
        </form>
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends 'layout.html' %}

{% block title %} Signup {% endblock %}

{% block content %}
    <div class="vh-100 d-flex align-items-center justify-content-center">
        <div>
            <h1>Sign Up</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Sign Up" class="btn btn-dark">
            </form>
        </div>
    </div>
{% endblock %}

templates/update_property.html
{% extends 'layout.html' %}

{% block title %}Update Property{% endblock %}

{% block content %}
<div class="d-flex justify-content-center" style="margin: 90px">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-dark">
    </form>
</div>
{% endblock %}

templates/update_service.html
{% extends 'layout.html' %}

{% block title %}Update Service{% endblock %}

{% block content %}
<div class="d-flex justify-content-center" style="margin: 90px">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" class="btn btn-dark">
    </form>
</div>
{% endblock %}